<?php

/**
 * BaseHintComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $hint_id
 * @property integer $comment_id
 * @property Hint $Hint
 * @property Comment $Comment
 * 
 * @method integer     getHintId()     Returns the current record's "hint_id" value
 * @method integer     getCommentId()  Returns the current record's "comment_id" value
 * @method Hint        getHint()       Returns the current record's "Hint" value
 * @method Comment     getComment()    Returns the current record's "Comment" value
 * @method HintComment setHintId()     Sets the current record's "hint_id" value
 * @method HintComment setCommentId()  Sets the current record's "comment_id" value
 * @method HintComment setHint()       Sets the current record's "Hint" value
 * @method HintComment setComment()    Sets the current record's "Comment" value
 * 
 * @package    By examples
 * @subpackage model
 * @author     gajdaw
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHintComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hint_has_comment');
        $this->hasColumn('hint_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Hint', array(
             'local' => 'hint_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}