<?php

/**
 * HintCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HintCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HintCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HintComment');
    }
}