<?php

/**
 * ProjectComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    By examples
 * @subpackage model
 * @author     gajdaw
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProjectComment extends BaseProjectComment
{

}