<?php

/**
 * ProjectCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectComment');
    }
}