<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('example_has_comment', 'example_has_comment_example_id_comments_id');
        $this->createForeignKey('comment', 'comment_created_by_sf_guard_user_id', array(
             'name' => 'comment_created_by_sf_guard_user_id',
             'local' => 'created_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('comment', 'comment_updated_by_sf_guard_user_id', array(
             'name' => 'comment_updated_by_sf_guard_user_id',
             'local' => 'updated_by',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('example_has_comment', 'example_has_comment_comment_id_comment_id', array(
             'name' => 'example_has_comment_comment_id_comment_id',
             'local' => 'comment_id',
             'foreign' => 'id',
             'foreignTable' => 'comment',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('example_has_comment', 'example_has_comment_example_id_comment_id', array(
             'name' => 'example_has_comment_example_id_comment_id',
             'local' => 'example_id',
             'foreign' => 'id',
             'foreignTable' => 'comment',
             ));
        $this->addIndex('comment', 'comment_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->addIndex('comment', 'comment_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->addIndex('example_has_comment', 'example_has_comment_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
        $this->addIndex('example_has_comment', 'example_has_comment_example_id', array(
             'fields' => 
             array(
              0 => 'example_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('example_has_comment', 'example_has_comment_example_id_comments_id', array(
             'name' => 'example_has_comment_example_id_comments_id',
             'local' => 'example_id',
             'foreign' => 'id',
             'foreignTable' => 'comments',
             ));
        $this->dropForeignKey('comment', 'comment_created_by_sf_guard_user_id');
        $this->dropForeignKey('comment', 'comment_updated_by_sf_guard_user_id');
        $this->dropForeignKey('example_has_comment', 'example_has_comment_comment_id_comment_id');
        $this->dropForeignKey('example_has_comment', 'example_has_comment_example_id_comment_id');
        $this->removeIndex('comment', 'comment_created_by', array(
             'fields' => 
             array(
              0 => 'created_by',
             ),
             ));
        $this->removeIndex('comment', 'comment_updated_by', array(
             'fields' => 
             array(
              0 => 'updated_by',
             ),
             ));
        $this->removeIndex('example_has_comment', 'example_has_comment_comment_id', array(
             'fields' => 
             array(
              0 => 'comment_id',
             ),
             ));
        $this->removeIndex('example_has_comment', 'example_has_comment_example_id', array(
             'fields' => 
             array(
              0 => 'example_id',
             ),
             ));
    }
}