options:
  collate: utf8_polish_ci
  charset: utf8
  type: InnoDB


Example:
  options:
    orderBy: number DESC
    collate: utf8_polish_ci
    charset: utf8
    type: InnoDB
  actAs:
    Signable:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: false
    Timestampable:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(128)
    lead:
      type: string(4096)
    contents:
      type: string(4096)
    number:
      type: integer
  relations:
    Comments:
      class: Comment
      refClass: ExampleComment


Project:
  options:
    orderBy: number DESC
    collate: utf8_polish_ci
    charset: utf8
    type: InnoDB
  actAs:
    Signable:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: false
    Timestampable:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(128)
    lead:
      type: string(4096)
    contents:
      type: string(4096)
    number:
      type: integer
  relations:
    Comments:
      class: Comment
      refClass: ProjectComment



Hint:
  options:
    orderBy: number DESC
    collate: utf8_polish_ci
    charset: utf8
    type: InnoDB
  actAs:
    Signable:
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: false
    Timestampable:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    title:
      type: string(128)
    lead:
      type: string(4096)
    contents:
      type: string(4096)
    number:
      type: integer
  relations:
    Comments:
      class: Comment
      refClass: HintComment



Comment:
  options:
    orderBy: created_at DESC
    collate: utf8_polish_ci
    charset: utf8
    type: InnoDB
  actAs:
    Signable:
    Timestampable:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    contents:
      type: string(4096)

  relations:
    Examples:
      class: Example
      refClass: ExampleComment

    Projects:
      class: Project
      refClass: ProjectComment

    Hints:
      class: Hint
      refClass: HintComment



ExampleComment:
  options:
    symfony:
      form:   false
      filter: false
  tableName: example_has_comment
  columns:
    example_id:
      type: integer
      primary: true
      notnull: true
    comment_id:
      type: integer
      primary: true
      notnull: true
  relations:
    Example:
      class: Example
      local: example_id
      foreign: id
      onDelete: CASCADE
    Comment:
      class: Comment
      local: comment_id
      foreign: id
      onDelete: CASCADE

ProjectComment:
  options:
    symfony:
      form:   false
      filter: false
  tableName: project_has_comment
  columns:
    project_id:
      type: integer
      primary: true
      notnull: true
    comment_id:
      type: integer
      primary: true
      notnull: true
  relations:
    Project:
      class: Project
      local: project_id
      foreign: id
      onDelete: CASCADE
    Comment:
      class: Comment
      local: comment_id
      foreign: id
      onDelete: CASCADE


HintComment:
  options:
    symfony:
      form:   false
      filter: false
  tableName: hint_has_comment
  columns:
    hint_id:
      type: integer
      primary: true
      notnull: true
    comment_id:
      type: integer
      primary: true
      notnull: true
  relations:
    Hint:
      class: Hint
      local: hint_id
      foreign: id
      onDelete: CASCADE
    Comment:
      class: Comment
      local: comment_id
      foreign: id
      onDelete: CASCADE
